server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/main

  profiles:
    include: "private"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true

  output:
    ansi:
      enabled: always